name: visenet2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=24.2
  - pthread-stubs=0.3
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.0.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lz4==4.3.3
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==10.4.0
      - polars==1.8.2
      - psutil==7.1.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - rosbags==0.9.23
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==2.1.0
      - ultralytics==8.3.239
      - ultralytics-thop==2.0.18
      - urllib3==2.2.3
      - zipp==3.20.2
      - zstandard==0.23.0